'use strict';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=n=>Number(n).toLocaleString('en-CA'),dec=n=>n===null?'—':n.toFixed(2),pct=n=>n===null?'—':(100*n).toFixed(1)+'%',money=c=>new Intl.NumberFormat('en-CA',{style:'currency',currency:'CAD',maximumFractionDigits:2}).format(c/100);
let data=structuredClone(BASELINE),actions={},page='overview',queuePage=0,editRow=null,filtered=[],programRows=[],monthRows=[],queueRows=[],timer,lastTarget=10;
const names={overview:['Payment performance','A measurable baseline, with a clear route from exceptions to follow-up.'],exceptions:['Exception desk','Prioritize, investigate and assign the next step.'],programs:['Program analysis','See where timing performance and exceptions concentrate.'],data:['Data & validation','Refresh the analysis and inspect the measurement rules.'],playbook:['Operating plan','A proposed weekly workflow to turn reporting into follow-through.']};
const key=()=> 'portfolio-kpi-actions-v2:'+data.id;
function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(timer);timer=setTimeout(()=>$('toast').hidden=true,5000);}
function readActions(){actions={};try{const v=JSON.parse(localStorage.getItem(key())||'{}');actions=validateActions(v);}catch(e){$('storageNote').textContent='Browser storage is unavailable or a saved action file is invalid. Use Export action backup to retain this session’s work.';}}
function saveActions(){try{localStorage.setItem(key(),JSON.stringify(actions));return true;}catch(e){$('storageNote').textContent='Actions are in memory only. Export action backup before closing this page.';return false;}}
function validateActions(obj){if(!obj||typeof obj!=='object'||Array.isArray(obj))throw Error('Invalid action object');const ids=new Set(data.rows.map(r=>String(r.row))),out={};for(const [id,a] of Object.entries(obj)){if(!ids.has(id)||!a||typeof a!=='object')throw Error('Action references an unknown source record');if(!['Not started','In progress','Waiting','Resolved'].includes(a.status))throw Error('Invalid action status');if(!['Not investigated','Payment scheduling','Approval delay','Source date issue','Provider details','Other / under review'].includes(a.cause))throw Error('Invalid cause');if(typeof a.owner!=='string'||a.owner.length>100||typeof a.note!=='string'||a.note.length>1500||typeof a.due!=='string'||typeof a.updated!=='string')throw Error('Invalid action fields');if(a.due)KPI.day(a.due);out[id]={owner:a.owner,note:a.note,due:a.due,status:a.status,cause:a.cause,updated:a.updated};}return out;}
function setPage(p){page=p;for(const [id,[title,desc]] of Object.entries(names)){$(id).hidden=id!==p;if(id===p){$('pageTitle').textContent=title;$('pageDesc').textContent=desc;}}document.querySelectorAll('[data-page]').forEach(b=>b.setAttribute('aria-current',b.dataset.page===p?'page':'false'));$('globalFilters').hidden=p==='data'||p==='playbook';$('scenario').hidden=p==='data'||p==='playbook';}
function options(){const oldM=$('month').value,oldP=$('program').value;$('month').innerHTML='<option value="all">All available months</option>'+[...new Set(data.rows.map(r=>r.month))].sort().map(m=>`<option value="${esc(m)}">${esc(m)}${m===data.asOf.slice(0,7)?' · partial':''}</option>`).join('');$('program').innerHTML='<option value="all">All programs</option>'+[...new Set(data.rows.map(r=>r.program))].sort().map(p=>`<option value="${esc(p)}">${esc(p)}</option>`).join('');if([...$('month').options].some(o=>o.value===oldM))$('month').value=oldM;if([...$('program').options].some(o=>o.value===oldP))$('program').value=oldP;}
function threshold(){return lastTarget;}
function statCard(label,value,sub){return `<div class="stat"><div class="label">${label}</div><div class="big">${value}</div><div class="meta">${sub}</div></div>`;}
function chart(rows,t){if(!rows.length)return '<p class="empty">No rows match these filters.</p>';let w=Math.max(300,Math.round($('trend').clientWidth||800)),h=285,left=48,right=25,top=25,bottom=45;let max=Math.max(1,t,...rows.map(x=>x.mean||0));max=Math.ceil(max*1.15);const y=v=>h-bottom-v/max*(h-bottom-top),x=i=>left+(rows.length===1?(w-left-right)/2:i/(rows.length-1)*(w-left-right));let svg=`<svg class="chart" viewBox="0 0 ${w} ${h}" role="img" aria-label="Average paid turnaround by System entry month, in calendar days"><title>Mean paid calendar days by entry month</title>`;for(let i=0;i<=4;i++){let v=max*i/4;svg+=`<line x1="${left}" x2="${w-right}" y1="${y(v)}" y2="${y(v)}" stroke="#e4eaf3"/><text x="${left-9}" y="${y(v)+4}" text-anchor="end">${v.toFixed(v%1?1:0)}</text>`;}svg+=`<line x1="${left}" x2="${w-right}" y1="${y(t)}" y2="${y(t)}" stroke="#bd852a" stroke-width="1.5" stroke-dasharray="5 5"/>`;let segments=[],segment=[];rows.forEach((r,i)=>{if(r.mean===null){if(segment.length)segments.push(segment);segment=[];}else segment.push(`${x(i)},${y(r.mean)}`)});if(segment.length)segments.push(segment);for(const seg of segments)svg+=`<polyline points="${seg.join(' ')}" fill="none" stroke="#2b62ea" stroke-width="3"/>`;rows.forEach((r,i)=>{let label=r.month==='Date review'?'Review':r.month.slice(5);if(r.mean!==null)svg+=`<circle cx="${x(i)}" cy="${y(r.mean)}" r="5" fill="#2b62ea" stroke="white" stroke-width="2"/>${(w>650||i%2===0)?`<text x="${x(i)}" y="${y(r.mean)-13}" text-anchor="middle" style="fill:#172d52;font-weight:bold">${r.mean.toFixed(2)}</text>`:''}`;if(i%Math.max(1,Math.ceil(rows.length/Math.max(2,Math.floor((w-left-right)/55))))===0)svg+=`<text x="${x(i)}" y="${h-20}" text-anchor="middle">${esc(label)}</text>`;});return svg+'</svg>';}
function refresh(){let t=Number($('target').value);if($('target').value.trim()===''||!Number.isInteger(t)||t<0||t>365){$('target').value=lastTarget;toast('Use a whole-number threshold from 0 to 365 days. Previous threshold retained.');return;}lastTarget=t;$('target').setCustomValidity('');filtered=data.rows.filter(r=>($('month').value==='all'||r.month===$('month').value)&&($('program').value==='all'||r.program===$('program').value));let s=KPI.stats(filtered,t);monthRows=KPI.monthly(filtered,t);const groups=new Map();for(const r of filtered){if(!groups.has(r.program))groups.set(r.program,[]);groups.get(r.program).push(r);}programRows=[...groups].map(([name,rows])=>({name,...KPI.stats(rows,t)})).sort((a,b)=>b.no-a.no||b.n-a.n||a.name.localeCompare(b.name));
 $('scenario').textContent=t===10?'Provisional benchmark: 10 calendar days. Confirm the operating definition and threshold with the process owner before formal adoption.':`SCENARIO: ${t} calendar days. This reclassifies existing records; the provisional baseline is 10 days.`;
 $('stats').innerHTML=statCard('Mean paid turnaround',dec(s.mean)+' <small>days</small>',`${num(s.paid)} valid paid records`)+statCard('Within selected threshold',pct(s.rate),`${num(s.yes)} of ${num(s.yes+s.no)} assessed records`)+statCard('Unpaid overdue',num(s.overdue),`${money(s.overdueCents)} signed net CAD · reconcile credits`)+statCard('Active payment records',num(s.n),`${num(s.review)} timing reviews · ${num(s.no)} outside`);
 $('trend').innerHTML=chart(monthRows,t);$('trendNote').textContent=`Source view · ${data.asOf.slice(0,7)} may be partial. Calendar-day scale starts at zero. Multiple years are identified in the scorecard below.`;
 const ranks=programRows.filter(x=>x.no>0).slice(0,5);$('ranks').innerHTML=ranks.length?ranks.map(r=>`<div class="rank"><div class="rank-top"><span class="rank-name">${esc(r.name)}</span><b>${num(r.no)}</b></div><div class="rank-track"><div class="rank-bar" style="width:${r.no/ranks[0].no*100}%"></div></div><div class="sub">${(100*r.no/r.n).toFixed(1)}% of program active records outside threshold</div></div>`).join(''):'<p class="empty">No outside-threshold records in this selection.</p>';
 let complete=monthRows.filter(x=>x.month<data.asOf.slice(0,7)&&x.mean!==null).at(-1);$('insight').innerHTML=complete?`<div class="insight-number">${dec(complete.mean)} d</div><p><b>${esc(complete.month)} paid turnaround</b><br>Latest complete entry month in this selection, versus ${dec(s.mean)} days across the selected records. Cohort differences alone do not establish a process improvement.</p>`:'<p>No complete entry month with valid paid records in this selection.</p>';
 $('monthly').innerHTML=monthRows.map(r=>`<tr><td>${esc(r.month)}${r.month===data.asOf.slice(0,7)?'<div class="sub">Partial month</div>':''}</td><td class="num">${num(r.n)}</td><td class="num">${num(r.paid)}</td><td class="num">${dec(r.mean)}</td><td class="num">${dec(r.median)}</td><td class="num">${dec(r.p90)}</td><td class="num">${pct(r.rate)}</td><td class="num">${num(r.no)}</td><td class="num">${num(r.review)}</td></tr>`).join('')||'<tr><td colspan="9" class="empty">No matching records</td></tr>';
 $('programTable').innerHTML=programRows.map((r,i)=>`<tr><td><button class="programLink" data-index="${i}">${esc(r.name)}</button></td><td class="num">${num(r.n)}</td><td class="num">${dec(r.mean)}</td><td class="num">${dec(r.p90)}</td><td class="num">${pct(r.rate)}</td><td class="num">${num(r.no)}</td><td class="num">${num(r.overdue)}</td><td class="num">${num(r.review)}</td></tr>`).join('');$('sensitivity').innerHTML=[5,10,15].map(v=>{let a=KPI.stats(filtered,v);return `<div class="fact"><b>${pct(a.rate)}</b><h3>Within ${v} days</h3><p class="meta">${num(a.no)} outside · ${num(a.review)} review${v===10?' · provisional baseline':''}</p></div>`;}).join('');
 renderQueue();renderData();$('footerSource').textContent=`${data.name} · as of ${data.asOf} · provider payment only`;}
function renderQueue(){const t=threshold(),all=filtered.filter(r=>['unpaid','review','late'].includes(KPI.type(r,t)));let s=KPI.stats(filtered,t);let assigned=all.filter(r=>actions[r.row]?.owner.trim()),resolved=all.filter(r=>actions[r.row]?.status==='Resolved');$('queueStats').innerHTML=statCard('Unpaid overdue',num(s.overdue),'Current aging within this snapshot')+statCard('Date / status reviews',num(s.review),'Validate against the source')+statCard('Exceptions with an owner',num(assigned.length),`${num(all.length)} total exception records`)+statCard('Follow-ups marked resolved',num(resolved.length),'Historical KPI outcomes stay unchanged');
 let query=$('search').value.trim().toLowerCase();queueRows=all.filter(r=>($('kind').value==='all'||KPI.type(r,t)===$('kind').value)&&($('workStatus').value==='all'||(actions[r.row]?.status||'Not started')===$('workStatus').value)&&(!query||r.program.toLowerCase().includes(query)||String(r.row).includes(query)));let priority={unpaid:0,review:1,late:2};queueRows.sort((a,b)=>priority[KPI.type(a,t)]-priority[KPI.type(b,t)]||(b.days??-1)-(a.days??-1)||b.cents-a.cents||a.row-b.row);const pageSize=15;queuePage=Math.max(0,Math.min(queuePage,Math.ceil(queueRows.length/pageSize)-1));let start=queuePage*pageSize;const labels={unpaid:['Unpaid overdue','amber'],review:['Timing review','red'],late:['Paid late','']};$('queue').innerHTML=queueRows.slice(start,start+pageSize).map(r=>{let a=actions[r.row],typ=KPI.type(r,t);return `<tr><td><b>#${r.row}</b><div class="sub">${esc(r.status)}</div></td><td>${esc(r.program)}<div class="sub">${esc(r.month)}</div></td><td><span class="pill ${labels[typ][1]}">${labels[typ][0]}</span>${r.review?`<div class="sub">${esc(r.reason)}</div>`:''}</td><td class="num">${r.days===null?'—':num(r.days)}</td><td class="num">${money(r.cents)}</td><td>${esc(a?.status||'Not started')}<div class="sub">${esc(a?.owner||'Unassigned')}${a?.due?' · '+esc(a.due):''}</div></td><td><button data-edit="${r.row}">Review</button></td></tr>`;}).join('')||'<tr><td colspan="7" class="empty">No exceptions match this selection.</td></tr>';$('pageCount').textContent=queueRows.length?`${num(start+1)}–${num(Math.min(start+pageSize,queueRows.length))} of ${num(queueRows.length)} exceptions`:'0 exceptions';$('prev').disabled=queuePage===0;$('next').disabled=start+pageSize>=queueRows.length;}
function renderData(){const s=KPI.stats(data.rows,10),c=data.counts;const excluded=c.canceled+c.closed;const unselected=data.rows.filter(r=>r.status==='Unselected').length;$('sourceInfo').innerHTML=`<p><b>${esc(data.name)}</b></p><p>Reporting date: <b>${esc(data.asOf)}</b><br>Business unit: CA01<br>Source fingerprint: <code style="overflow-wrap:anywhere">${esc(data.id)}</code></p><p><b>${num(c.raw)} raw = ${num(c.other)} other-unit + ${num(excluded)} excluded + ${num(s.n)} active</b></p><p>${num(c.canceled)} Canceled · ${num(c.closed)} Closed<br>${num(s.yes)} within + ${num(s.no)} outside + ${num(s.review)} review = ${num(s.n)} active at 10 days.<br>${num(unselected)} Unselected records.</p>`;$('reconciliation').innerHTML=`<div class="fact"><b>${num(s.paid)}</b><span class="meta">Valid paid rows</span></div><div class="fact"><b>${num(s.review)}</b><span class="meta">Timing reviews</span></div><div class="fact"><b>${num(c.duplicates)}</b><span class="meta">Repeated active rows retained</span></div>`;let warnings=[];if(c.duplicates)warnings.push(`${num(c.duplicates)} repeated identical active rows are retained. Check the extract before formal reporting.`);if(s.review)warnings.push(`${num(s.review)} records have invalid or conflicting timing and are excluded from timing denominators.`);$('qualityWarnings').innerHTML=warnings.map(w=>`<div class="callout">${esc(w)}</div>`).join('');}
function openAction(id){const r=data.rows.find(x=>x.row===id);if(!r)return;editRow=id;let a=actions[id]||{owner:'',status:'Not started',cause:'Not investigated',due:'',note:''};$('actionRef').textContent=`Source record #${id} · ${r.month}`;$('actionEvidence').textContent=`${r.program} · ${r.status} · ${r.days===null?'date unavailable':r.days+' days'} · ${money(r.cents)}${r.reason?' · '+r.reason:''}`;for(const f of ['owner','cause','due','note'])$(f).value=a[f];$('actionStatus').value=a.status;$('actionDialog').showModal();}
function download(name,contents,type){const blob=new Blob([contents],{type}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function csvCell(v){let s=String(v??'');if(typeof v==='string'&&/^[\s]*[=+\-@]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';}
function exportCsv(name,rows){if(!rows.length){toast('No rows to export for this selection.');return;}const keys=Object.keys(rows[0]);download(name,'\uFEFF'+[keys.map(csvCell).join(','),...rows.map(r=>keys.map(k=>csvCell(r[k])).join(','))].join('\r\n'),'text/csv;charset=utf-8');}
function exportStat(r){return {active:r.n,valid_paid:r.paid,mean_paid_days:r.mean,median_paid_days:r.median,p90_paid_days:r.p90,within:r.yes,outside:r.no,review:r.review,within_percent:r.rate===null?'':100*r.rate,unpaid_overdue:r.overdue,base_CAD:r.cents/100,threshold_days:threshold(),as_of:data.asOf,source:data.name,program_filter:$('program').value,month_filter:$('month').value};}
async function fingerprint(buffer){if(globalThis.crypto?.subtle){const h=await crypto.subtle.digest('SHA-256',buffer);return [...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,'0')).join('');}let h=2166136261;for(const byte of new Uint8Array(buffer)){h^=byte;h=Math.imul(h,16777619);}return 'fnv1a32-'+(h>>>0).toString(16).padStart(8,'0')+'-'+buffer.byteLength;}
async function importFile(){const f=$('sourceFile').files[0];if(!f){status('Choose a Canada payment CSV first.',false);return;}if(f.size>50*1024*1024){status('Use a CSV smaller than 50 MB for this local prototype.',false);return;}$('import').disabled=true;status('Reading and validating the source…',true);try{const buffer=await f.arrayBuffer(),text=new TextDecoder($('encoding').value,{fatal:true}).decode(buffer),id=await fingerprint(buffer),next=KPI.ingest(text,$('asOf').value,f.name,id);if(next.counts.raw!==next.counts.other+next.counts.canceled+next.counts.closed+next.rows.length)throw Error('Source reconciliation failed');data=next;actions={};readActions();$('month').value='all';$('program').value='all';$('target').value=10;queuePage=0;options();refresh();status(`Loaded ${num(data.rows.length)} active Canada records from ${f.name}. See Source & reconciliation for checks.`,true);}catch(e){status(e.message+' Your prior dataset remains available.',false);}finally{$('import').disabled=false;}}
function status(text,ok){$('importStatus').hidden=false;$('importStatus').className=ok?'success':'alert';$('importStatus').textContent=text;}
document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>setPage(b.dataset.page));$('loadTop').onclick=()=>setPage('data');$('print').onclick=()=>window.print();for(const id of ['month','program','target'])$(id).onchange=()=>{queuePage=0;refresh();};$('reset').onclick=()=>{$('month').value='all';$('program').value='all';$('target').value=10;$('kind').value='all';$('workStatus').value='all';$('search').value='';queuePage=0;refresh();};for(const id of ['kind','workStatus'])$(id).onchange=()=>{queuePage=0;renderQueue();};$('search').oninput=()=>{queuePage=0;renderQueue();};$('prev').onclick=()=>{queuePage--;renderQueue();};$('next').onclick=()=>{queuePage++;renderQueue();};$('queue').onclick=e=>{const b=e.target.closest('[data-edit]');if(b)openAction(Number(b.dataset.edit));};$('programTable').onclick=e=>{let b=e.target.closest('.programLink');if(b){$('program').value=programRows[Number(b.dataset.index)].name;queuePage=0;refresh();setPage('overview');}};for(const id of ['closeDialog','cancelDialog'])$(id).onclick=()=>$('actionDialog').close();$('actionForm').onsubmit=e=>{e.preventDefault();actions[editRow]={owner:$('owner').value.trim(),status:$('actionStatus').value,cause:$('cause').value,due:$('due').value,note:$('note').value.trim(),updated:new Date().toISOString()};const saved=saveActions();$('actionDialog').close();renderQueue();toast(saved?'Follow-up saved in this browser.':'Follow-up saved for this session. Export a backup before closing.');};
$('exportMonthly').onclick=()=>exportCsv('payment_monthly_KPI.csv',monthRows.map(r=>({month:r.month,...exportStat(r)})));$('exportPrograms').onclick=()=>exportCsv('payment_program_KPI.csv',programRows.map(r=>({program:r.name,...exportStat(r)})));$('exportQueue').onclick=()=>exportCsv('payment_exception_queue.csv',queueRows.map(r=>({source_record:r.row,program:r.program,entry_month:r.month,source_status:r.status,exception:KPI.type(r,threshold()),days:r.days,base_CAD:r.cents/100,reason:r.reason,owner:actions[r.row]?.owner||'',action_status:actions[r.row]?.status||'Not started',cause:actions[r.row]?.cause||'',next_review:actions[r.row]?.due||'',next_step:actions[r.row]?.note||'',threshold_days:threshold(),as_of:data.asOf,source_fingerprint:data.id})));
$('backup').onclick=()=>download('payment_action_backup.json',JSON.stringify({version:2,sourceId:data.id,sourceName:data.name,asOf:data.asOf,actions},null,2),'application/json');$('restore').onchange=async()=>{const f=$('restore').files[0];if(!f)return;try{if(f.size>10*1024*1024)throw Error('Backup is too large');const b=JSON.parse(await f.text());if(b.version!==2||b.sourceId!==data.id)throw Error('This backup belongs to a different source file or version');const incoming=validateActions(b.actions);for(const [id,a] of Object.entries(incoming)){if(!actions[id]||a.updated>actions[id].updated)actions[id]=a;}saveActions();renderQueue();toast('Matching actions restored. Newer saved actions were retained.');}catch(e){toast('Backup not restored: '+e.message);}$('restore').value='';};
$('auditExport').onclick=()=>download('payment_KPI_audit.json',JSON.stringify({source:data.name,source_fingerprint:data.id,as_of:data.asOf,counts:data.counts,baseline_threshold_days:10,baseline:KPI.stats(data.rows,10),current_filters:{month:$('month').value,program:$('program').value,threshold_days:threshold()},current_results:KPI.stats(filtered,threshold()),definition:'CA01 active voucher/payment rows; exclude Canceled/Closed. AcctgDate system-entry proxy; UTC calendar-day differences. Review excluded from assessed denominator. BaseGrossAmount assumed CAD. Target provisional.',exported_at:new Date().toISOString()},null,2),'application/json');$('import').onclick=importFile;$('sample').onclick=()=>{data=structuredClone(BASELINE);actions={};readActions();$('month').value='all';$('program').value='all';$('target').value=10;$('asOf').value=data.asOf;$('sourceFile').value='';queuePage=0;options();refresh();status('Synthetic demo restored. Saved baseline follow-ups remain available.',true);};
readActions();options();refresh();setPage('overview');

if(typeof ResizeObserver!=='undefined'){new ResizeObserver(()=>{if(page==='overview')$('trend').innerHTML=chart(monthRows,threshold());}).observe($('trend'));}
