'use strict';
const groups={Buyer:[['buyerNI','Net income ($m)'],['buyerShares','Shares (m)'],['buyerPrice','Share price ($)']],Target:[['targetNI','Net income ($m)'],['targetShares','Shares (m)'],['targetPrice','Unaffected price ($)'],['targetDebt','Existing debt ($m)'],['targetCash','Cash ($m)'],['targetEBITDA','EBITDA ($m)']],Transaction:[['premium','Offer premium (%)'],['stockPct','Stock funding (%)'],['cashPct','Existing cash (%)'],['interest','New debt rate (%)'],['cashYield','Cash yield (%)'],['tax','Marginal tax (%)']],Execution:[['synergies','Run-rate synergies ($m)'],['realization','Synergy realization (%)'],['amortization','Incremental amort. ($m)'],['fees','One-time fees ($m)']]};
const money=v=>v.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2}),pct=v=>(v*100).toFixed(1)+'%';let current={...DealLens.defaults},result;
const inputs=document.getElementById('inputs');
for(const [name,fields] of Object.entries(groups)){const fs=document.createElement('fieldset');const lg=document.createElement('legend');lg.textContent=name;fs.append(lg);for(const [key,label]of fields){let l=document.createElement('label');l.className='field';l.textContent=label;let i=document.createElement('input');i.type='number';i.step='any';i.id=key;i.value=current[key];i.required=true;i.addEventListener('input',refresh);l.append(i);fs.append(l)}inputs.append(fs)}
function refresh(){let next={};for(const k of Object.keys(DealLens.defaults)){let el=document.getElementById(k);next[k]=el.value.trim()===''?NaN:Number(el.value)}let error=document.getElementById('error');try{result=DealLens.calculate(next);current=next;error.hidden=true;document.querySelector('article').hidden=false;for(const id of ['save','memo','csv'])document.getElementById(id).disabled=false;draw()}catch(e){error.textContent=e.message;error.hidden=false;document.querySelector('article').hidden=true;for(const id of ['save','memo','csv'])document.getElementById(id).disabled=true;result=null}}
function set(a){for(const k of Object.keys(DealLens.defaults))document.getElementById(k).value=a[k];refresh()}
function draw(){const r=result;
 const baseline=DealLens.calculate(DealLens.defaults);
 const delta=(r.accretion-baseline.accretion)*100;
 const gap=r.breakEven===null?null:r.realizedSynergies-r.breakEven;
 document.getElementById('snapshot').innerHTML=`<div class="scenario-line"><b class="${r.accretion>=0?'positive-text':'negative-text'}">${r.accretion>=0?'Recurring EPS accretive':'Recurring EPS dilutive'}</b><span>${delta>=0?'+':''}${delta.toFixed(2)} percentage points vs. default example</span></div><p class="small">${gap===null?'Synergy break-even unavailable at a 100% tax rate.':gap>=0?'Realized synergies exceed the nonnegative EPS-neutral threshold by $'+money(gap)+'m.':'An additional $'+money(-gap)+'m in realized pre-tax synergies is needed for recurring EPS neutrality.'} Review year-one fees and financing capacity separately.</p>`;
 const epsItems=[['Standalone buyer',r.standaloneEPS],['Recurring pro forma',r.eps],['Year-one pro forma',r.yearOneEPS]];
 const scale=Math.max(...epsItems.map(x=>Math.abs(x[1])),0.01);
 document.getElementById('epsChart').innerHTML='<p class="chart-label">EARNINGS PER SHARE / USD</p>'+epsItems.map(([label,v],i)=>`<div class="eps-row"><span>${label}</span><div class="bar-track"><div class="eps-bar bar-${i} ${v<0?'negative-bar':''}" style="width:${Math.abs(v)/scale*100}%"></div></div><b>$${money(v)}</b></div>`).join('')+'<p class="small">Bar length shows absolute EPS; signed values appear at right.</p>';
 document.getElementById('fundingChart').innerHTML='<div class="funding-stack" aria-hidden="true">'+[['stock',r.stock],['cash',r.cash],['debt',r.debt]].map(([label,v])=>`<div class="${label}" style="width:${v/r.equity*100}%"></div>`).join('')+'</div><div class="funding-legend">'+[['stock',r.stock],['cash',r.cash],['debt',r.debt]].map(([label,v])=>`<span><i class="${label}"></i>${label==='cash'?'Existing cash':label==='debt'?'New debt':'Stock'} <b>${pct(v/r.equity)}</b></span>`).join('')+'</div>';
document.getElementById('metrics').innerHTML=[['Recurring EPS impact',pct(r.accretion),'Pro forma EPS $'+money(r.eps)],['Year-one EPS impact',pct(r.yearOneAccretion),'Includes $'+money(current.fees)+'m of fees'],['Enterprise value','$'+money(r.ev)+'m',money(r.multiple)+'x target EBITDA'],['EPS-neutral synergies',r.breakEven===null?'Unavailable':'$'+money(r.breakEven)+'m','Required realized pre-tax annual synergies']].map(([a,b,c])=>`<div class="metric"><small>${a}</small><strong>${b}</strong><p>${c}</p></div>`).join('');
 document.getElementById('funding').innerHTML=[['Equity purchase price',r.equity],['Stock consideration',r.stock],['Existing buyer cash',r.cash],['New acquisition debt',r.debt],['Sources minus consideration',r.sourceCheck]].map(([n,v])=>`<div class="fundrow"><span>${n}</span><b>$${money(v)}m</b></div>`).join('')+`<p class="small">New shares: ${money(r.newShares)}m · Combined shares: ${money(r.totalShares)}m · Standalone EPS: $${money(r.standaloneEPS)}</p>`;
 document.getElementById('bridge').innerHTML=r.rows.map(([n,v],i)=>`<tr class="${i===6||i===8?'total':''}"><td>${n}</td><td>${money(v)}</td></tr>`).join('');
 document.getElementById('sensitivity').innerHTML='<thead><tr><th>Premium / synergy</th>'+[0,5,10,15,20].map(x=>`<th>$${x}m</th>`).join('')+'</tr></thead><tbody>'+DealLens.sensitivity(current).map(x=>`<tr><th>${x.premium}%</th>${x.cells.map(v=>`<td class="${v>=0?'pos':'neg'}">${pct(v)}</td>`).join('')}</tr>`).join('')+'</tbody>';
 document.getElementById('questions').innerHTML=`<p><b>Execution:</b> The model realizes $${money(r.realizedSynergies)}m of annual synergies. Identify owners, timing and integration costs before underwriting this assumption.</p><p><b>Funding:</b> $${money(r.debt)}m of new debt adds $${money(r.interestExpense)}m in annual pre-tax interest. Validate financing capacity and covenant headroom separately.</p><p><b>Value:</b> The offer implies ${money(r.multiple)}x EBITDA. Compare the premium with standalone value, comparable companies and downside outcomes; EPS accretion is not a substitute for valuation.</p>`;
}
function download(name,text,type){let url=URL.createObjectURL(new Blob([text],{type}));let a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
document.getElementById('reset').onclick=()=>set({...DealLens.defaults});document.getElementById('downside').onclick=()=>set({...DealLens.defaults,realization:35,interest:9,fees:12});document.getElementById('save').onclick=()=>download('deallens-assumptions.json',JSON.stringify({schemaVersion:1,dataType:'hypothetical',assumptions:current},null,2),'application/json');
document.getElementById('loadButton').onclick=()=>document.getElementById('load').click();
document.getElementById('load').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>100000)throw Error('Assumption file exceeds 100KB.');let data=JSON.parse(await f.text());if(data.schemaVersion!==1)throw Error('Unsupported schema version.');DealLens.calculate(data.assumptions);set(data.assumptions)}catch(err){document.getElementById('error').textContent='Import rejected: '+err.message;document.getElementById('error').hidden=false}e.target.value=''};
document.getElementById('csv').onclick=()=>download('deallens-earnings-bridge.csv','Component,USD millions\n'+result.rows.map(([n,v])=>`"${n}",${v.toFixed(6)}`).join('\n'),'text/csv');
document.getElementById('memo').onclick=()=>download('deallens-deal-memo.txt',`DEALLENS — HYPOTHETICAL ACQUISITION REVIEW\nGenerated ${new Date().toISOString()}\n\nEquity consideration: $${money(result.equity)}m\nEnterprise value: $${money(result.ev)}m (${money(result.multiple)}x EBITDA)\nFunding: stock $${money(result.stock)}m / cash $${money(result.cash)}m / new debt $${money(result.debt)}m\nRecurring EPS impact: ${pct(result.accretion)}\nYear-one EPS impact: ${pct(result.yearOneAccretion)}\nRequired realized synergies for EPS neutrality: ${result.breakEven===null?'Unavailable':'$'+money(result.breakEven)+'m'}\n\nDILIGENCE\nValidate financing capacity, synergy timing, integration costs and standalone value. EPS accretion does not establish value creation.\n\nASSUMPTIONS\n${JSON.stringify(current,null,2)}\n\nLIMITATIONS\nEducational prototype with hypothetical data. Full-year model; target debt and cash retained. Fees paid separately from buyer cash, expensed without tax benefit; financing costs on fees omitted. No full purchase accounting, refinancing, cash flow model, market data or investment advice.\n`,'text/plain');refresh();
